spring:
  application:
    name: gateway-micro-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: USERS-MICRO-SERVER
          uri: lb://USERS-MICRO-SERVER
          predicates:
            - Path=/api/user/**, /api/v2/admin/**

        - id: SALON-MICRO-SERVER
          uri: lb://SALON-MICRO-SERVER
          predicates:
            - Path=/api/salon/**

        - id: CATEGORY-SERVER
          uri: lb://CATEGORY-SERVER
          predicates:
            - Path=/api/category/**

        - id: BOOKING-SERVICE-SERVER
          uri: lb://BOOKING-SERVICE-SERVER
          predicates:
            - Path=/api/booking-service/**

        - id: AUTH-SERVER
          uri: lb://AUTH-SERVER
          predicates:
            - Path=/api/v1/auth/**

        - id: PAYMENT-SERVER
          uri: lb://PAYMENT-SERVER
          predicates:
            - Path=/api/payment/**

        - id: SERVICE-OFFERING-SERVER
          uri: lb://SERVICE-OFFERING-SERVER
          predicates:
            - Path=/api/service-offer/**, /api/owner/service-offering/**

server:
  port: 5000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8060/eureka/
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG

jwt:
  secret: bXktc2VjcmV0LWtleS0xMjM0NTY3ODkwMTIzNDU2o4387qry87m7x748y7q7y0a898w8adwe87ny7ze9ya37ty97ew
  access-token-expiration: 900000
  refresh-token-expiration: 604800000